apiVersion: apps/v1

kind: Deployment

metadata:
  name: backend
  labels: 
    app: backend

spec:
  replicas: 2
  selector:
    matchLabels:
      labels:
        app: backend
  containers:
    - name: backend
      images: jenagan/job-portal-backend:latest
      ports:
        containerPort: 4000
    