apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  ports:
  - name: "frontend-service"
    port: 80
    targetPort: 3000
  selector:
    app: frontend
  type: LoadBalancer
