apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
spec:
  accessModes:
    - ReadWriteOnce  # Allows the volume to be mounted as read-write by a single node
  resources:
    requests:
      storage: 10Gi  # Requesting 10 GiB of storage
  storageClassName: standard  # Specify the storage class (adjust as necessary)
