apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: jena-job-portal
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-class
  resources:
    requests:
      storage: 15Gi