apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  # namespace: expense-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 27017
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: mydb
          volumeMounts:
            - name: postgres-data  # Corrected volume name reference
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data  # Add this volume definition
          persistentVolumeClaim:
            claimName: postgres-pvc  # Ensure it matches the PVC name
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  # namespace: jena-job-portal
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  # namespace: expense-tracker  # Correct namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Make sure it matches the volume size of the PV
  storageClassName: ebs-class  # Ensure this matches the storage class of the PV
