name: CI-Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: |
         cd backend
         npm install

      - name: Check package.json
        run: |
         cd backend
         cat package.json

      - name: Build Project
        run: |
          cd backend
          npm run build

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Set up kubectl
        uses: kubectl/actions/setup-kubectl@v2
        with:
          kubectl-version: 'v1.32.0'

      - name: Configure kubectl to access EKS
        run: |
          aws eks update-kubeconfig --name jena-cluster --region eu-west-1

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/backend-deployment.yaml  
          kubectl rollout status deployment/backend 

      - name: Notify Deployment Success
        run: |
          echo "Deployment successful!"
