name: CI-Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: |
         cd backend
         npm install

      - name: Check package.json
        run: |
         cd backend
         cat package.json

      - name: Build Project
        run: |
          cd backend
          npm run build

      - name: Deploy
        run: |
          echo "Deploying app..."